### ISSUE TITLE
Why is the SharpSpades project a .dll and not an .exe?

### ISSUE THREAD

**Issue by luizfernandonb** [JStalnac/SharpSpades#6]
In the SharpSpades solution the SharpSpades project is a class library and not an `.exe`, but if we wanted to distribute an `.exe` for Ace of Spades players to create their own servers, what would that look like? An `.exe` is much easier besides that it doesn't make much sense for the server itself to be a `.dll`

**Comment by JStalnac** [comment]
I'm intending to add plugin support and the plugins will be class libraries. A class library can't reference an `Exe` project in .NET, so we need to have an api/core project that the plugins use. I figured that that the current configuration is the best solution because of accessibility issues that would break the usability of the api.
EDIT: You know what I mean
